version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projectManagerDB
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=password
    volumes:
      - /data/mysql
  spring-boot-jpa-app:
    image: project-manager-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app
 